### ISSUE TITLE
output direct link of upload to cli or file

### ISSUE THREAD

**Issue by cobra2** [sigflup/yesplz#1]
Would it be possible to output the direct link to the image posted to the terminal or to a specified file? 

It would be awesome to be able to specify a file and just have yesplz append entries to the end of the file. I think that the location of the file can be derived without any queries to the server. This magic number that needs to be found is already being seen in a -dump. Just run an upload and look for "my_gallery" then look for "index.php?cat=" and there will lie the magic number. I have not tested if this changes when files are put into a different album, if it does another method of discovery may be required.

Here is a method of verification.
- click on a previous uploaded image from the user to view it in full screen
- the path should be something like unixporn.ml/albums/userpics/$galley/image.jpg
- have the user either specify on the command line -gallery or save it in .yesplz.cfg

The path unixporn.ml/albums/userpics/ is static, the only parts that change are $USERID based on the user and the image that yesplz generates. Which I'm sure yesplz keeps track of the image name seeing as it has to upload the file.

**Comment by sigflup** [comment]
Do you want the link to go directly into the clip board?

**Comment by cobra2** [comment]
Can that be an option rather than a default behavior?

**Comment by sigflup** [comment]
sure

**Comment by sigflup** [comment]
Ugh sigflup_test has been banned

**Comment by sigflup** [comment]
Ok, I'm done. I'll add in clipboard support later. I've committed the
changes to the github repo

**Comment by cobra2** [comment]
Vewy nice!
http://unixporn.ml/displayimage.php?pid=65&fullsize=1

I checked on sigflup_test, user appears to be registered and not banned.

**Comment by sigflup** [comment]
I think klaatu fixed the ban

**Comment by cobra2** [comment]
This should be closed right?

**Comment by sigflup** [comment]
got it
